name: Buckle Linux CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build
    - name: Test
      run: RUST_BACKTRACE=1 cargo test
    - name: Lint
      run: cargo clippy